trigger:
  branches:
    include:
      - main

stages:
- stage: Deploy
  displayName: 'Deploy AWS Infrastructure'
  jobs:
  - job: Terraform_Apply
    displayName: 'Terraform Apply'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.5.0'

    - script: terraform init
      displayName: 'Terraform Init'

    - script: terraform plan
      displayName: 'Terraform Plan'

    - task: ManualValidation@0
      inputs:
        notifyUsers: '["admin@example.com"]'
        instructions: 'Por favor, revisa el plan antes de aplicar'
        onTimeout: 'reject'

    - script: terraform apply -auto-approve
      displayName: 'Terraform Apply'
